name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Deno fmt (backend functions)
        run: deno fmt --check backend/supabase/functions
      - name: Deno lint (backend functions)
        run: deno lint backend/supabase/functions
      - name: Placeholder tests
        run: 'echo "TODO: add Vitest/Playwright and RLS/contract harness"'
